    int socket_mqtt_connect(int, string, void | int, void | string);
    int socket_mqtt_disconnect(int);
    mapping socket_mqtt_status(int);
    int socket_mqtt_publish(int, string, string, void | int, void | int);
    int socket_mqtt_subscribe(int, string | string *, void | int | int *);
    int socket_mqtt_unsubscribe(int, string | string *);
    int socket_mqtt_set_config(int, mapping);
    mapping socket_mqtt_get_config(int);
    int socket_mqtt_set_will(int, string, string, void | int, void | int);
    int socket_mqtt_clear_will(int);