int socket_mqtt_connect(int socket_fd, string broker_host, int broker_port | void, string client_id | void);
int socket_mqtt_disconnect(int socket_fd);
mapping socket_mqtt_status(int socket_fd);
int socket_mqtt_publish(int socket_fd, string topic, string payload, int qos | void, int retain | void);
int socket_mqtt_subscribe(int socket_fd, string | string * topic, int | int * qos | void);
int socket_mqtt_unsubscribe(int socket_fd, string | string * topic);
int socket_mqtt_set_config(int socket_fd, mapping config);
mapping socket_mqtt_get_config(int socket_fd);
int socket_mqtt_set_will(int socket_fd, string topic, string message, int qos | void, int retain | void);
int socket_mqtt_clear_will(int socket_fd);